const BOOKS = [
  {
    id: "example-book",
    emoji: "📕",
    titleHr: "Primjer knjige",
    titleEn: "Example Book",
    lines: [
      { hr: "Ovo je primjer rečenice.", en: "This is an example sentence." },
      { hr: "Svaki redak može biti cijela stranica, jedna rečenica, ili samo dio rečenice - ti biraš.", en: "Each line can be a whole page, one sentence, or just part of a sentence - you choose." },
      { hr: "Ovo je treći i posljednji redak ovog primjera.", en: "This is the third and final line of this example." },
    ],
  },
];

// Words that must lead into the next clause, never trail the previous one
// (conjunctions and short prepositions) - used by splitSentence() below.
// Duplicated from stories.js rather than shared, matching this project's
// pattern of self-contained data files with no cross-file dependencies.
const BOOK_LEADING_WORDS = new Set([
  "i", "ali", "pa", "te", "ili", "nego", "jer",
  "u", "na", "do", "od", "za", "sa", "s", "po", "iz", "kroz", "uz", "niz",
]);

// Auxiliary clitics that stay attached to the participle before them
// (e.g. "živjela je", not "živjela" / "je ...") - used by splitSentence() below.
const BOOK_TRAILING_CLITICS = new Set(["je", "sam", "si", "smo", "ste", "su"]);

function stripBookWord(word) {
  return word.replace(/[.,!?"]+$/, "").toLowerCase();
}

// Splits a sentence into two halves for "Polako" (slow) mode - see stories.js
// for the full rationale. Identical logic, applied to BOOKS instead of STORIES.
function splitBookSentence(text) {
  const commaIdx = text.indexOf(",");
  if (commaIdx !== -1 && commaIdx > text.length * 0.25 && commaIdx < text.length * 0.75) {
    return [text.slice(0, commaIdx + 1).trim(), text.slice(commaIdx + 1).trim()];
  }

  const words = text.split(" ");
  let mid = Math.ceil(words.length / 2);

  if (mid > 1 && BOOK_LEADING_WORDS.has(stripBookWord(words[mid - 1]))) {
    mid -= 1;
  }
  if (mid < words.length - 1 && BOOK_TRAILING_CLITICS.has(stripBookWord(words[mid]))) {
    mid += 1;
  }

  return [words.slice(0, mid).join(" "), words.slice(mid).join(" ")];
}

// Audio file path convention: audio/<bookId>/lineNN.mp3 (1-indexed, zero-padded to 2 digits) -
// the same audio/ root Stories already uses; book ids just need to stay unique across the app.
// Slow-mode halves are separate files: audio/<bookId>/lineNN-slow-a.mp3 / -slow-b.mp3.
// Generated by scripts/generate-audio.js, same as stories.
BOOKS.forEach((book) => {
  book.lines.forEach((line, i) => {
    const n = String(i + 1).padStart(2, "0");
    line.audio = `audio/${book.id}/line${n}.mp3`;
    line.audioSlowA = `audio/${book.id}/line${n}-slow-a.mp3`;
    line.audioSlowB = `audio/${book.id}/line${n}-slow-b.mp3`;
    const [half1, half2] = splitBookSentence(line.hr);
    line.hrHalf1 = half1;
    line.hrHalf2 = half2;
  });
});

// Node (generate-audio.js) needs this; browsers ignore it since `module` is undefined.
if (typeof module !== "undefined") module.exports = BOOKS;
