const SONGS = [
  {
    id: "three-little-birds",
    title: "Three Little Birds",
    artist: "Bob Marley",
    key: "A",
    capo: null,
    sections: [
      { label: "Intro", chords: ["A"], lines: [] },
      { label: "Chorus", chords: ["A", "D", "A", "D"], lines: ["Don't worry about a thing,", "'Cause every little thing gonna be all right. Singin':", "Don't worry about a thing,", "'Cause every little thing gonna be all right"] },
      { label: "Verse 1", chords: ["A", "E", "A", "D", "A", "E", "D", "A"], lines: ["Rise up this mornin', Smile with the risin' sun,", "Three little birds", "Pitch by my doorstep", "Singin' sweet songs", "Of melodies pure and true,", "Sayin:", "\"This is my message to you\""] },
      { label: "Chorus", chords: ["A", "D", "A", "D"], lines: ["Singin':", "Don't worry about a thing,", "'Cause every little thing gonna be all right. Singin':", "Don't worry about a thing,"] },
      { label: "Verse 2", chords: ["A", "E", "A", "D", "A", "E", "D", "A"], lines: ["'Cause every little thing gonna be all right", "Rise up this mornin', Smile with the risin' sun,", "Three little birds", "Pitch by my doorstep", "Singin' sweet songs", "Of melodies pure and true,", "Sayin:"] },
      { label: "Outro", chords: ["A", "D", "A", "D"], lines: ["\"This is my message to you", "Singin':", "Don't worry about a thing,", "'Cause every little thing gonna be all right. Singin':"] },
      { label: "Fade Out", chords: ["A", "D", "A", "D"], lines: ["Don't worry about a thing,", "'Cause every little thing gonna be all right", "Singin':", "Don't worry about a thing,", "'Cause every little thing gonna be all right. Singin':", "Don't worry about a thing,", "'Cause every little thing gonna be all right"] },
    ],
  },
  {
    id: "house-of-the-rising-sun",
    title: "House of the Rising Sun",
    artist: "The Animals",
    key: "Am",
    capo: null,
    sections: [
      { label: "Intro", chords: ["Am", "C", "D", "F", "Am", "E", "Am", "E"], lines: [] },
      { label: "Verse 1", chords: ["Am", "C", "D", "F", "Am", "C", "E", "E", "Am", "C", "D", "F", "Am", "E", "Am", "C", "D", "F", "Am", "E", "Am", "E"], lines: ["There is a house in New Orleans", "They call the \"Rising Sun\"", "And it's been the ruin of many a poor boy", "And God, I know, I'm one"] },
      { label: "Verse 2", chords: ["Am", "C", "D", "F", "Am", "C", "E", "E", "Am", "C", "D", "F", "Am", "E", "Am", "C", "D", "F", "Am", "E", "Am", "E"], lines: ["My mother was a tailor", "She sewed my new blue jeans", "My father was a gambling man", "Down in New Orleans."] },
      { label: "Verse 3", chords: ["Am", "C", "D", "F", "Am", "C", "E", "E", "Am", "C", "D", "F", "Am", "E", "Am", "C", "D", "F", "Am", "E", "Am", "E"], lines: ["Now the only thing a gambler needs", "Is a suitcase and a trunk", "And the only time, he's satisfied,", "Is when he's on a drunk"] },
      { label: "Organ Solo", chords: ["Am", "C", "D", "F", "Am", "C", "E", "E", "Am", "C", "D", "F", "Am", "E", "Am", "C/E", "D", "F", "Am", "E", "Am", "E"], lines: [] },
      { label: "Verse 4", chords: ["Am", "C", "D", "F", "Am", "C", "E", "E", "Am", "C", "D", "F", "Am", "E", "Am", "C", "D", "F", "Am", "E", "Am", "E"], lines: ["Oh, mother, tell your children", "Not to do what I have done", "Spend your lives in sin and misery", "In the House of the Rising Sun"] },
      { label: "Verse 5", chords: ["Am", "C", "D", "F", "Am", "C", "E", "E", "Am", "C", "D", "F", "Am", "E", "Am", "C", "D", "F", "Am", "E", "Am", "E"], lines: ["Well, I got one foot on the platform", "The other foot on the train", "I'm going back to New Orleans", "To wear that ball and chain"] },
      { label: "Verse 6", chords: ["Am", "C", "D", "F", "Am", "C", "E", "E", "Am", "C", "D", "F", "Am", "E7", "Am", "C", "D", "F7", "Am", "E7"], lines: ["Well, there is a house in New Orleans", "They call the \"Rising Sun\"", "And it's been the ruin of many a poor boy", "And God, I know, I'm one"] },
      { label: "Coda", chords: ["Am", "Dm", "Am", "Dm", "Am", "Dm", "Am", "Dm", "Am", "Dm", "Am"], lines: [] },
    ],
  },
  {
    id: "have-you-ever-seen-the-rain",
    title: "Have You Ever Seen the Rain",
    artist: "Creedence Clearwater Revival",
    key: "C",
    capo: null,
    sections: [
      { label: "Intro", chords: ["Am", "F/C", "C", "G", "C"], lines: [] },
      { label: "Verse", chords: ["C", "C", "G", "C", "C", "C", "G", "C"], lines: ["Someone told me long ago", "There's a calm before the storm, I know", "It's been coming for some time", "When it's over, so they say", "It'll rain a sunny day, I know", "Shining down like water"] },
      { label: "Chorus", chords: ["F", "G", "C", "C/B", "Am", "Am7/G", "F", "G", "C", "C/B", "Am", "Am7/G", "F", "G", "C"], lines: ["I wanna know", "Have you ever seen the rain", "I wanna know", "Have you ever seen the rain", "Coming down on a sunny day"] },
      { label: "Verse", chords: ["C", "C", "G", "C", "C", "C", "G", "C"], lines: ["Yesterday and days before", "Sun is cold and rain is hard, I know", "Been that way for all my time", "'Til forever on it goes", "Through the circle fast and slow, I know", "It can't stop, I wonder"] },
      { label: "Chorus", chords: ["F", "G", "C", "C/B", "Am", "Am7/G", "F", "G", "C", "C/B", "Am", "Am7/G", "F", "G", "C"], lines: ["I wanna know", "Have you ever seen the rain", "I wanna know", "Have you ever seen the rain", "Coming down on a sunny day"] },
      { label: "Chorus", chords: ["F", "G", "C", "C/B", "Am", "Am7/G", "F", "G", "C", "C/B", "Am", "Am7/G", "F", "G", "C", "G", "C"], lines: ["I wanna know", "Have you ever seen the rain", "I wanna know", "Have you ever seen the rain", "Coming down on a sunny day"] },
    ],
  },
  {
    id: "be-my-baby",
    title: "Be My Baby",
    artist: "The Ronettes",
    key: "E",
    capo: null,
    sections: [
      { label: "Intro", chords: ["E"], lines: [] },
      { label: "Verse 1", chords: ["E", "F#m", "B7", "E", "F#m", "B7"], lines: ["The night we met I knew I    needed you so", "And if I had the chance I'd    never let you go"] },
      { label: "Pre-Chorus", chords: ["G#7", "C#7", "F#", "B7", "E"], lines: ["So won't you say you love me", "I'll make you so proud of me", "We'll make 'em turn their heads every place we go", "So won't you, please"] },
      { label: "Chorus", chords: ["C#m", "A", "B7"], lines: ["Be my little baby,", "Say you'll be my darlin',", "Be my baby now", "Wha oh oh oh"] },
      { label: "Verse 2", chords: ["E", "F#m", "B7", "E", "F#m", "B7"], lines: ["I'll make you happy, baby,    just wait and see", "For every kiss you give me    I'll give you three"] },
      { label: "Pre-Chorus", chords: ["G#7", "C#7", "F#", "B7", "E"], lines: ["Oh, since the day I saw you", "I have been waiting for you", "You know I will adore you 'til eternity", "So won't you, please"] },
      { label: "Chorus", chords: ["C#m", "A", "B7"], lines: ["Be my little baby,", "Say you'll be my darlin',", "Be my baby now", "Wha oh oh oh"] },
      { label: "Strings Solo", chords: ["F#m", "B7", "E", "F#m", "B7", "E"], lines: [] },
      { label: "Chorus", chords: ["C#m", "A", "B7", "E", "C#m", "A", "B7"], lines: ["So come on and, please", "Be my little baby,", "Say you'll be my darlin',", "Be my baby now"] },
      { label: "Outro (Fade out)", chords: ["E", "C#m", "A", "B7"], lines: ["Wha oh oh oh", "Be my baby now"] },
    ],
  },
  {
    id: "landslide",
    title: "Landslide",
    artist: "Fleetwood Mac",
    key: "C",
    capo: null,
    sections: [
      { label: "Intro", chords: ["C", "G/B", "Am7", "G/B", "C", "G/B", "Am7", "G/B"], lines: [] },
      { label: "Verse 1", chords: ["C", "G/B", "Am7", "G/B", "C", "G/B", "Am7", "G/B", "C", "G/B", "Am7", "G/B", "C", "G/B", "Am7"], lines: ["I took my love,    I took it down", "I climbed a mountain and I turned around", "And I saw my reflection in the snowcovered hills", "'Till the landslide brought me down"] },
      { label: "Verse 2", chords: ["G/B", "C", "G/B", "Am7", "G/B", "C", "G/B", "Am7", "G/B", "C", "G/B", "Am7", "G/B", "C", "G/B", "Am7", "G/B", "C", "G/B", "Am7", "D7/F#"], lines: ["Oh, mirror in the sky,    what is love?", "Can the child within my heart rise above?", "Can I sail through the changing ocean tides?", "Can I handle the seasons of     my life?", "Mmm."] },
      { label: "Chorus", chords: ["G", "D/F#", "D7/F#", "Em", "C", "G/B", "Am7", "D7/F#", "G", "D/F#", "D7/F#", "Em", "C", "G/B", "Am7", "G/B"], lines: ["Well, I've been afraid    of      changing", "'Cause I've built my life    around you", "But time makes you bolder, even", "Children get older", "And I'm getting older too"] },
      { label: "Solo", chords: ["C", "G/B", "Am7", "G/B", "C", "G/B", "Am7", "G/B", "C", "G/B", "Am7", "G/B", "C", "G/B"], lines: [] },
      { label: "Chorus", chords: ["Am7", "D7/F#", "G", "D/F#", "D7/F#", "Em", "C", "G/B", "Am7", "D7/F#", "G", "D/F#", "D7/F#", "Em", "C", "G/B", "Am7", "G/B"], lines: ["Well, I've been afraid     of     changing", "'Cause I've built my life    around you", "But time makes you bolder, even", "Children get older", "And I'm getting older too", "Oh I'm getting older too"] },
      { label: "Verse 3", chords: ["C", "G/B", "Am7", "G/B", "C", "G/B", "Am7", "G/B", "C", "G/B", "Am7", "G/B", "C", "G/B", "Am7", "G/B", "C", "G/B", "Am"], lines: ["Ah, take my love, take it down", "Ah, climb a mountain and turn around", "And if you see my reflection in the snowcovered hills", "Well the landslide will bring it down", "And if you see my reflection in the snowcovered hills", "Well the landslide will bring it down    Oh", "the landslide will bring it down"] },
    ],
  },
  {
    id: "were-going-to-be-friends",
    title: "We're Going to Be Friends",
    artist: "The White Stripes",
    key: "G",
    capo: null,
    sections: [
      { label: "Intro", chords: ["G"], lines: [] },
      { label: "Verse 1", chords: ["G", "C", "G", "D", "C", "G", "D", "C", "G"], lines: ["Fall is here, hear the yell", "Back to school, ring the bell", "Brand new shoes, walking blues", "Climb the fence, books and pens", "I can tell that we are going to be friends", "I can tell that we are going to be friends"] },
      { label: "Verse 2", chords: ["G", "C", "G", "D", "C", "G", "D", "C", "G"], lines: ["Walk with me, Suzy Lee", "Through the park and by the tree", "We can rest upon the ground", "And look at all the bugs we've found", "Safely walk to school without a sound", "Safely walk to school without a sound"] },
      { label: "Verse 3", chords: ["G", "C", "G", "D", "C", "G", "D", "C", "G"], lines: ["Here we are no one else", "We walk to school all by ourselves", "There's dirt on our uniforms", "From chasing all the ants and worms", "We clean up and now it's time to learn", "We clean up and now it's time to learn"] },
      { label: "Verse 4", chords: ["G", "C", "G", "D", "C", "G", "D", "C", "G"], lines: ["Numbers, letters, learn to spell", "Nouns and books and show and tell", "Play time, we will throw the ball", "Back to class through the hall", "Teacher marks our height against the wall", "Teacher marks our height against the wall"] },
      { label: "Bridge", chords: ["C", "G", "C", "G", "A", "C", "D"], lines: ["And we don't notice any time pass", "We don't notice anything", "We sit side by side in every class", "Teacher thinks that I sound funny", "but she likes the way you sing"] },
      { label: "Verse 5", chords: ["G", "C", "G", "D", "C", "G", "D", "C", "G6"], lines: ["Tonight I'll dream while in my bed", "While silly thoughts run through my head", "About the bugs and alphabet", "When I wake tomorrow I'll bet", "That you and I will walk together again", "I can tell that we are going to be friends", "I can tell that we are going to be friends"] },
    ],
  },
  {
    id: "bad-moon-rising",
    title: "Bad Moon Rising",
    artist: "Creedence Clearwater Revival",
    key: "D",
    capo: null,
    sections: [
      { label: "Intro", chords: ["D", "A", "G", "D"], lines: [] },
      { label: "Verse 1", chords: ["D", "A", "G", "D", "D", "A", "G", "D", "D", "A", "G", "D", "D", "A", "G", "D"], lines: ["", "", "", ""] },
      { label: "Chorus", chords: ["G", "D", "A", "G", "D"], lines: ["", "", ""] },
      { label: "Verse 2", chords: ["D", "A", "G", "D", "D", "A", "G", "D", "D", "A", "G", "D", "D", "A", "G", "D"], lines: ["", "", "", ""] },
      { label: "Chorus", chords: ["G", "D", "A", "G", "D"], lines: ["", "", ""] },
      { label: "Solo", chords: ["D", "A", "G", "D", "D", "A", "G", "D", "G", "D", "A", "G", "D"], lines: [] },
      { label: "Verse 3", chords: ["D", "A", "G", "D", "D", "A", "G", "D", "D", "A", "G", "D", "D", "A", "G", "D"], lines: ["", "", "", ""] },
      { label: "Chorus", chords: ["G", "D", "A", "G", "D"], lines: ["", "", ""] },
      { label: "Outro", chords: ["G", "D", "A", "G", "D"], lines: ["", "", ""] },
    ],
  },
  {
    id: "girl-from-the-north-country",
    title: "Girl from the North Country (Duet)",
    artist: "Bob Dylan",
    key: "G",
    capo: null,
    sections: [
      { label: "Intro", chords: ["G", "Bm", "C", "G", "G", "G", "G"], lines: [] },
      { label: "Verse 1", chords: ["G", "Bm", "C", "G", "G", "Bm", "C", "G", "G", "Bm", "C", "G", "G", "Bm", "C", "G"], lines: ["If you're travelin'     in the north country fair,", "Where the winds hit heavy on the borderline,", "Remember me to one who lives there.", "For she once was a true love of mine."] },
      { label: "Verse 2", chords: ["G", "Bm", "C", "G", "G", "Bm", "C", "G", "G", "Bm", "C", "G", "G", "Bm", "C", "G"], lines: ["See for me that her hair's hanging down,", "It curls and falls all down her breast.", "See for me that her hair's hanging down,", "That's the way I remember her best."] },
      { label: "Verse 3", chords: ["G", "Bm", "C", "G", "G", "Bm", "C", "G", "G", "Bm", "C", "G", "G", "Bm", "C", "G"], lines: ["If you go when the snowflakes fall,", "When the rivers freeze and summer ends,", "Please see for me if she's wearing a coat so warm,", "To keep her from the howlin' winds."] },
      { label: "Verse 4", chords: ["G", "Bm", "C", "G", "G", "Bm", "C", "G", "G", "Bm", "C", "G", "G", "Bm", "C", "G"], lines: ["If you're travelin' in the north country fair,", "Where the winds hit heavy on the borderline,", "Please say hello to one who lives there.", "For she once was a true love of mine."] },
      { label: "Interlude", chords: ["G", "Bm", "C", "G", "G", "Bm", "C", "G"], lines: [] },
      { label: "Verse 5", chords: ["G", "Bm", "C", "G", "G", "Bm", "C", "G", "G", "Bm", "C", "G", "G", "Bm", "C", "G"], lines: ["If you're travelin' in the north country fair,", "Where the winds hit heavy on the borderline,", "Remember me to one who lives there.", "She once was a true love of mine."] },
      { label: "Outro", chords: ["Bm", "C", "G", "Bm", "C", "G", "Bm", "C", "G"], lines: ["True love of mine. A true love of mine.", "true love of mine. True love of mine. A true love of mine.", "true love of mine. She was once a true love of mine."] },
    ],
  },
  {
    id: "youre-still-the-one",
    title: "You're Still the One",
    artist: "Shania Twain",
    key: "D",
    capo: null,
    sections: [
      { label: "Intro", chords: ["D", "D", "G", "A"], lines: [] },
      { label: "Verse 1", chords: ["D", "G", "A", "D", "G", "A", "D", "G", "A", "D", "G", "A", "D", "G", "A"], lines: ["Looks like we made it, Look how far we've come my baby", "We mighta took the long way, We knew we'd get there someday", "They said, \"I bet they'll never make it\"", "But just look at us holding on", "We're still together still going strong", "You're still the one", "You're still the one I run to"] },
      { label: "Chorus", chords: ["G", "D", "G", "Em", "A", "D", "G", "A", "G", "D", "G", "Em", "A", "D", "G", "A"], lines: ["The one that I belong to", "You're still the one I want for life", "You're still the one", "You're still the one that I love", "The only one I dream of", "You're still the one I kiss good night", "Ain't nothin' better", "We beat the odds together"] },
      { label: "Verse 2", chords: ["D", "G", "A", "D", "G", "A", "D", "G", "A", "D", "G", "A", "D", "G", "A"], lines: ["I'm glad we didn't listen", "Look at what we would be missin'", "They said, \"I bet they'll never make it\"", "But just look at us holding on", "We're still together still going strong", "You're still the one", "You're still the one I run to"] },
      { label: "Chorus", chords: ["G", "D", "G", "Em", "A", "D", "G", "A", "G", "D", "G", "Em", "A", "D", "G", "A"], lines: ["The one that I belong to", "You're still the one I want for life", "You're still the one", "You're still the one that I love", "The only one I dream of", "You're still the one I kiss good night", "You're still the one", "You're still the one I run to"] },
      { label: "Solo", chords: ["D", "G", "A"], lines: [] },
      { label: "Chorus", chords: ["G", "D", "G", "Em", "A", "D", "G", "A", "G", "D", "G", "Em", "A", "D", "G", "A"], lines: ["The one that I belong to", "You're still the one I want for life", "You're still the one", "You're still the one that I love", "The only one I dream of", "You're still the one I kiss good night", "I'm so glad we made it", "Look how far we've come my baby"] },
      { label: "Tag", chords: ["D", "G", "A"], lines: ["", ""] },
    ],
  },
];

// Node (scripts/fill-song-lyrics.js) needs this; browsers ignore it since `module` is undefined.
if (typeof module !== "undefined") module.exports = SONGS;
