const SONGS = [
  {
    id: "three-little-birds",
    title: "Three Little Birds",
    artist: "Bob Marley",
    key: "A",
    capo: null,
    sections: [
      { label: "Intro", chords: ["A"], lines: [] },
      { label: "Chorus", chords: ["A", "D", "A", "D"], lines: ["", "", "", ""] },
      { label: "Verse 1", chords: ["A", "E", "A", "D", "A", "E", "D", "A"], lines: ["", "", "", "", "", "", ""] },
      { label: "Chorus", chords: ["A", "D", "A", "D"], lines: ["", "", "", ""] },
      { label: "Verse 2", chords: ["A", "E", "A", "D", "A", "E", "D", "A"], lines: ["", "", "", "", "", "", ""] },
      { label: "Outro", chords: ["A", "D", "A", "D"], lines: ["", "", "", ""] },
      { label: "Fade Out", chords: ["A", "D", "A", "D"], lines: ["", "", "", ""] },
    ],
  },
  {
    id: "house-of-the-rising-sun",
    title: "House of the Rising Sun",
    artist: "The Animals",
    key: "Am",
    capo: null,
    sections: [
      { label: "Intro", chords: ["Am", "C", "D", "F", "Am", "E", "Am", "E"], lines: [] },
      { label: "Verse 1", chords: ["Am", "C", "D", "F", "Am", "C", "E", "E", "Am", "C", "D", "F", "Am", "E", "Am", "C", "D", "F", "Am", "E", "Am", "E"], lines: ["", "", "", ""] },
      { label: "Verse 2", chords: ["Am", "C", "D", "F", "Am", "C", "E", "E", "Am", "C", "D", "F", "Am", "E", "Am", "C", "D", "F", "Am", "E", "Am", "E"], lines: ["", "", "", ""] },
      { label: "Verse 3", chords: ["Am", "C", "D", "F", "Am", "C", "E", "E", "Am", "C", "D", "F", "Am", "E", "Am", "C", "D", "F", "Am", "E", "Am", "E"], lines: ["", "", "", ""] },
      { label: "Organ Solo", chords: ["Am", "C", "D", "F", "Am", "C", "E", "E", "Am", "C", "D", "F", "Am", "E", "Am", "C/E", "D", "F", "Am", "E", "Am", "E"], lines: [] },
      { label: "Verse 4", chords: ["Am", "C", "D", "F", "Am", "C", "E", "E", "Am", "C", "D", "F", "Am", "E", "Am", "C", "D", "F", "Am", "E", "Am", "E"], lines: ["", "", "", ""] },
      { label: "Verse 5", chords: ["Am", "C", "D", "F", "Am", "C", "E", "E", "Am", "C", "D", "F", "Am", "E", "Am", "C", "D", "F", "Am", "E", "Am", "E"], lines: ["", "", "", ""] },
      { label: "Verse 6", chords: ["Am", "C", "D", "F", "Am", "C", "E", "E", "Am", "C", "D", "F", "Am", "E7", "Am", "C", "D", "F7", "Am", "E7"], lines: ["", "", "", ""] },
      { label: "Coda", chords: ["Am", "Dm", "Am", "Dm", "Am", "Dm", "Am", "Dm", "Am", "Dm", "Am"], lines: [] },
    ],
  },
  {
    id: "have-you-ever-seen-the-rain",
    title: "Have You Ever Seen the Rain",
    artist: "Creedence Clearwater Revival",
    key: "C",
    capo: null,
    sections: [
      { label: "Intro", chords: ["Am", "F/C", "C", "G", "C"], lines: [] },
      { label: "Verse", chords: ["C", "C", "G", "C", "C", "C", "G", "C"], lines: ["", "", "", "", "", ""] },
      { label: "Chorus", chords: ["F", "G", "C", "C/B", "Am", "Am7/G", "F", "G", "C", "C/B", "Am", "Am7/G", "F", "G", "C"], lines: ["", "", "", "", ""] },
      { label: "Verse", chords: ["C", "C", "G", "C", "C", "C", "G", "C"], lines: ["", "", "", "", "", ""] },
      { label: "Chorus", chords: ["F", "G", "C", "C/B", "Am", "Am7/G", "F", "G", "C", "C/B", "Am", "Am7/G", "F", "G", "C"], lines: ["", "", "", "", ""] },
      { label: "Chorus", chords: ["F", "G", "C", "C/B", "Am", "Am7/G", "F", "G", "C", "C/B", "Am", "Am7/G", "F", "G", "C", "G", "C"], lines: ["", "", "", "", ""] },
    ],
  },
  {
    id: "be-my-baby",
    title: "Be My Baby",
    artist: "The Ronettes",
    key: "E",
    capo: null,
    sections: [
      { label: "Intro", chords: ["E"], lines: [] },
      { label: "Verse 1", chords: ["E", "F#m", "B7", "E", "F#m", "B7"], lines: ["", ""] },
      { label: "Pre-Chorus", chords: ["G#7", "C#7", "F#", "B7", "E"], lines: ["", "", "", ""] },
      { label: "Chorus", chords: ["C#m", "A", "B7"], lines: ["", "", "", ""] },
      { label: "Verse 2", chords: ["E", "F#m", "B7", "E", "F#m", "B7"], lines: ["", ""] },
      { label: "Pre-Chorus", chords: ["G#7", "C#7", "F#", "B7", "E"], lines: ["", "", "", ""] },
      { label: "Chorus", chords: ["C#m", "A", "B7"], lines: ["", "", "", ""] },
      { label: "Strings Solo", chords: ["F#m", "B7", "E", "F#m", "B7", "E"], lines: [] },
      { label: "Chorus", chords: ["C#m", "A", "B7", "E", "C#m", "A", "B7"], lines: ["", "", "", ""] },
      { label: "Outro (Fade out)", chords: ["E", "C#m", "A", "B7"], lines: [""] },
    ],
  },
  {
    id: "landslide",
    title: "Landslide",
    artist: "Fleetwood Mac",
    key: "C",
    capo: null,
    sections: [
      { label: "Intro", chords: ["C", "G/B", "Am7", "G/B", "C", "G/B", "Am7", "G/B"], lines: [] },
      { label: "Verse 1", chords: ["C", "G/B", "Am7", "G/B", "C", "G/B", "Am7", "G/B", "C", "G/B", "Am7", "G/B", "C", "G/B", "Am7"], lines: ["", "", "", ""] },
      { label: "Verse 2", chords: ["G/B", "C", "G/B", "Am7", "G/B", "C", "G/B", "Am7", "G/B", "C", "G/B", "Am7", "G/B", "C", "G/B", "Am7", "G/B", "C", "G/B", "Am7", "D7/F#"], lines: ["", "", "", "", ""] },
      { label: "Chorus", chords: ["G", "D/F#", "D7/F#", "Em", "C", "G/B", "Am7", "D7/F#", "G", "D/F#", "D7/F#", "Em", "C", "G/B", "Am7", "G/B"], lines: ["", "", "", "", ""] },
      { label: "Solo", chords: ["C", "G/B", "Am7", "G/B", "C", "G/B", "Am7", "G/B", "C", "G/B", "Am7", "G/B", "C", "G/B"], lines: [] },
      { label: "Chorus", chords: ["Am7", "D7/F#", "G", "D/F#", "D7/F#", "Em", "C", "G/B", "Am7", "D7/F#", "G", "D/F#", "D7/F#", "Em", "C", "G/B", "Am7", "G/B"], lines: ["", "", "", "", "", ""] },
      { label: "Verse 3", chords: ["C", "G/B", "Am7", "G/B", "C", "G/B", "Am7", "G/B", "C", "G/B", "Am7", "G/B", "C", "G/B", "Am7", "G/B", "C", "G/B", "Am"], lines: ["", "", "", "", "", ""] },
    ],
  },
  {
    id: "were-going-to-be-friends",
    title: "We're Going to Be Friends",
    artist: "The White Stripes",
    key: "G",
    capo: null,
    sections: [
      { label: "Intro", chords: ["G"], lines: [] },
      { label: "Verse 1", chords: ["G", "C", "G", "D", "C", "G", "D", "C", "G"], lines: ["", "", "", "", "", ""] },
      { label: "Verse 2", chords: ["G", "C", "G", "D", "C", "G", "D", "C", "G"], lines: ["", "", "", "", "", ""] },
      { label: "Verse 3", chords: ["G", "C", "G", "D", "C", "G", "D", "C", "G"], lines: ["", "", "", "", "", ""] },
      { label: "Verse 4", chords: ["G", "C", "G", "D", "C", "G", "D", "C", "G"], lines: ["", "", "", "", "", ""] },
      { label: "Bridge", chords: ["C", "G", "C", "G", "A", "C", "D"], lines: ["", "", "", "", ""] },
      { label: "Verse 5", chords: ["G", "C", "G", "D", "C", "G", "D", "C", "G6"], lines: ["", "", "", "", "", "", ""] },
    ],
  },
  {
    id: "bad-moon-rising",
    title: "Bad Moon Rising",
    artist: "Creedence Clearwater Revival",
    key: "D",
    capo: null,
    sections: [
      { label: "Intro", chords: ["D", "A", "G", "D"], lines: [] },
      { label: "Verse 1", chords: ["D", "A", "G", "D", "D", "A", "G", "D", "D", "A", "G", "D", "D", "A", "G", "D"], lines: ["", "", "", ""] },
      { label: "Chorus", chords: ["G", "D", "A", "G", "D"], lines: ["", "", ""] },
      { label: "Verse 2", chords: ["D", "A", "G", "D", "D", "A", "G", "D", "D", "A", "G", "D", "D", "A", "G", "D"], lines: ["", "", "", ""] },
      { label: "Chorus", chords: ["G", "D", "A", "G", "D"], lines: ["", "", ""] },
      { label: "Solo", chords: ["D", "A", "G", "D", "D", "A", "G", "D", "G", "D", "A", "G", "D"], lines: [] },
      { label: "Verse 3", chords: ["D", "A", "G", "D", "D", "A", "G", "D", "D", "A", "G", "D", "D", "A", "G", "D"], lines: ["", "", "", ""] },
      { label: "Chorus", chords: ["G", "D", "A", "G", "D"], lines: ["", "", ""] },
      { label: "Outro", chords: ["G", "D", "A", "G", "D"], lines: ["", "", ""] },
    ],
  },
  {
    id: "girl-from-the-north-country",
    title: "Girl from the North Country (Duet)",
    artist: "Bob Dylan",
    key: "G",
    capo: null,
    sections: [
      { label: "Intro", chords: ["G", "Bm", "C", "G", "G", "G", "G"], lines: [] },
      { label: "Verse 1", chords: ["G", "Bm", "C", "G", "G", "Bm", "C", "G", "G", "Bm", "C", "G", "G", "Bm", "C", "G"], lines: ["", "", "", ""] },
      { label: "Verse 2", chords: ["G", "Bm", "C", "G", "G", "Bm", "C", "G", "G", "Bm", "C", "G", "G", "Bm", "C", "G"], lines: ["", "", "", ""] },
      { label: "Verse 3", chords: ["G", "Bm", "C", "G", "G", "Bm", "C", "G", "G", "Bm", "C", "G", "G", "Bm", "C", "G"], lines: ["", "", "", ""] },
      { label: "Verse 4", chords: ["G", "Bm", "C", "G", "G", "Bm", "C", "G", "G", "Bm", "C", "G", "G", "Bm", "C", "G"], lines: ["", "", "", ""] },
      { label: "Interlude", chords: ["G", "Bm", "C", "G", "G", "Bm", "C", "G"], lines: [] },
      { label: "Verse 5", chords: ["G", "Bm", "C", "G", "G", "Bm", "C", "G", "G", "Bm", "C", "G", "G", "Bm", "C", "G"], lines: ["", "", "", ""] },
      { label: "Outro", chords: ["Bm", "C", "G", "Bm", "C", "G", "Bm", "C", "G"], lines: ["", "", ""] },
    ],
  },
  {
    id: "youre-still-the-one",
    title: "You're Still the One",
    artist: "Shania Twain",
    key: "D",
    capo: null,
    sections: [
      { label: "Intro", chords: ["D", "D", "G", "A"], lines: [] },
      { label: "Verse 1", chords: ["D", "G", "A", "D", "G", "A", "D", "G", "A", "D", "G", "A", "D", "G", "A"], lines: ["", "", "", "", "", "", ""] },
      { label: "Chorus", chords: ["G", "D", "G", "Em", "A", "D", "G", "A", "G", "D", "G", "Em", "A", "D", "G", "A"], lines: ["", "", "", "", "", "", "", ""] },
      { label: "Verse 2", chords: ["D", "G", "A", "D", "G", "A", "D", "G", "A", "D", "G", "A", "D", "G", "A"], lines: ["", "", "", "", "", "", ""] },
      { label: "Chorus", chords: ["G", "D", "G", "Em", "A", "D", "G", "A", "G", "D", "G", "Em", "A", "D", "G", "A"], lines: ["", "", "", "", "", "", "", ""] },
      { label: "Solo", chords: ["D", "G", "A"], lines: [] },
      { label: "Chorus", chords: ["G", "D", "G", "Em", "A", "D", "G", "A", "G", "D", "G", "Em", "A", "D", "G", "A"], lines: ["", "", "", "", "", "", "", ""] },
      { label: "Tag", chords: ["D", "G", "A"], lines: ["", ""] },
    ],
  },
];
