// Generated by scripts/update-weekly-stories.js for week of 2026-09-07.
// Do not edit by hand — change scripts/story-bank.js and re-run.

const WEEK = {
  "STORY_DATE": "2026-09-07",
  "STORY_DATE_HR": "tjedan 7. rujna 2026.",
  "PREVIOUS_DATE": null,
  "PREVIOUS_STORIES": [],
  "STORIES": [
    {
      "id": "s-tara",
      "emoji": "🛝",
      "weekDate": "2026-09-07",
      "titleHr": "Tara uči ples",
      "titleEn": "Tara teaches him to dance",
      "focusHr": "učiti",
      "focusEn": "to teach",
      "lines": [
        {
          "hr": "Tara pali glazbu u sobi.",
          "en": "Tara puts music on in the room.",
          "audio": "audio/s-tara/2026-09-07/line01.mp3"
        },
        {
          "hr": "Tara kaže hajde Nikoli sad.",
          "en": "Tara says come on to Nikola now.",
          "audio": "audio/s-tara/2026-09-07/line02.mp3"
        },
        {
          "hr": "Tara uči ga plesati sad.",
          "en": "Tara teaches him to dance now.",
          "audio": "audio/s-tara/2026-09-07/line03.mp3"
        },
        {
          "hr": "Ona pokazuje mu jedan korak.",
          "en": "She shows him one step.",
          "audio": "audio/s-tara/2026-09-07/line04.mp3"
        },
        {
          "hr": "Nikola ponavlja taj korak polako.",
          "en": "Nikola repeats that step slowly.",
          "audio": "audio/s-tara/2026-09-07/line05.mp3"
        },
        {
          "hr": "Tara pleše polako pred njim.",
          "en": "Tara dances slowly in front of him.",
          "audio": "audio/s-tara/2026-09-07/line06.mp3"
        },
        {
          "hr": "Nikola pleše za njom skupa.",
          "en": "Nikola dances along with her.",
          "audio": "audio/s-tara/2026-09-07/line07.mp3"
        },
        {
          "hr": "Ona daje mu ruku sad.",
          "en": "She gives him her hand now.",
          "audio": "audio/s-tara/2026-09-07/line08.mp3"
        },
        {
          "hr": "Nikola hoće još jedan korak.",
          "en": "Nikola wants one more step.",
          "audio": "audio/s-tara/2026-09-07/line09.mp3"
        },
        {
          "hr": "Oni plešu skupa po sobi.",
          "en": "They dance together around the room.",
          "audio": "audio/s-tara/2026-09-07/line10.mp3"
        }
      ]
    },
    {
      "id": "s-baka",
      "emoji": "🍪",
      "weekDate": "2026-09-07",
      "titleHr": "Baka na tržnici",
      "titleEn": "Baka at the market",
      "focusHr": "kupovati",
      "focusEn": "to buy",
      "lines": [
        {
          "hr": "Baka i Nikola idu na tržnicu.",
          "en": "Baka and Nikola go to the market.",
          "audio": "audio/s-baka/2026-09-07/line01.mp3"
        },
        {
          "hr": "Nikola vidi crvene rajčice tamo.",
          "en": "Nikola sees red tomatoes there.",
          "audio": "audio/s-baka/2026-09-07/line02.mp3"
        },
        {
          "hr": "Baka hoće svježi kruh danas.",
          "en": "Baka wants fresh bread today.",
          "audio": "audio/s-baka/2026-09-07/line03.mp3"
        },
        {
          "hr": "Ona daje mu jednu krušku.",
          "en": "She gives him one pear.",
          "audio": "audio/s-baka/2026-09-07/line04.mp3"
        },
        {
          "hr": "Nikola kaže hvala svojoj baki.",
          "en": "Nikola says thank you to his baka.",
          "audio": "audio/s-baka/2026-09-07/line05.mp3"
        },
        {
          "hr": "Baka kupuje sir za kuću.",
          "en": "Baka buys cheese for the house.",
          "audio": "audio/s-baka/2026-09-07/line06.mp3"
        },
        {
          "hr": "Oni nose vrećice prema kući.",
          "en": "They carry the bags toward home.",
          "audio": "audio/s-baka/2026-09-07/line07.mp3"
        },
        {
          "hr": "Nikola ide uz baku polako.",
          "en": "Nikola walks slowly beside baka.",
          "audio": "audio/s-baka/2026-09-07/line08.mp3"
        },
        {
          "hr": "Baka pokazuje mu žute limune.",
          "en": "Baka shows him yellow lemons.",
          "audio": "audio/s-baka/2026-09-07/line09.mp3"
        },
        {
          "hr": "Oni se vraćaju kući skupa.",
          "en": "They come back home together.",
          "audio": "audio/s-baka/2026-09-07/line10.mp3"
        }
      ]
    },
    {
      "id": "s-odlazak",
      "emoji": "🚲",
      "weekDate": "2026-09-07",
      "titleHr": "Lopta s tatom",
      "titleEn": "A ball with tata",
      "focusHr": "trčati",
      "focusEn": "to run",
      "lines": [
        {
          "hr": "Tata donosi loptu u dvorište.",
          "en": "Tata brings a ball into the yard.",
          "audio": "audio/s-odlazak/2026-09-07/line01.mp3"
        },
        {
          "hr": "Nikola vidi loptu u travi.",
          "en": "Nikola sees the ball in the grass.",
          "audio": "audio/s-odlazak/2026-09-07/line02.mp3"
        },
        {
          "hr": "Tata kaže hajde prema njemu.",
          "en": "Tata says come on toward him.",
          "audio": "audio/s-odlazak/2026-09-07/line03.mp3"
        },
        {
          "hr": "Nikola hoće udariti tu loptu.",
          "en": "Nikola wants to kick that ball.",
          "audio": "audio/s-odlazak/2026-09-07/line04.mp3"
        },
        {
          "hr": "Tata daje mu loptu prvo.",
          "en": "Tata gives him the ball first.",
          "audio": "audio/s-odlazak/2026-09-07/line05.mp3"
        },
        {
          "hr": "Nikola udara loptu prema tati.",
          "en": "Nikola kicks the ball toward tata.",
          "audio": "audio/s-odlazak/2026-09-07/line06.mp3"
        },
        {
          "hr": "Oni trče skupa za loptom.",
          "en": "They run together after the ball.",
          "audio": "audio/s-odlazak/2026-09-07/line07.mp3"
        },
        {
          "hr": "Tata ide u gol sad.",
          "en": "Tata goes in goal now.",
          "audio": "audio/s-odlazak/2026-09-07/line08.mp3"
        },
        {
          "hr": "Nikola šalje loptu u gol.",
          "en": "Nikola sends the ball into the goal.",
          "audio": "audio/s-odlazak/2026-09-07/line09.mp3"
        },
        {
          "hr": "Tata tapše ga zbog pogotka.",
          "en": "Tata claps for him because of the goal.",
          "audio": "audio/s-odlazak/2026-09-07/line10.mp3"
        }
      ]
    },
    {
      "id": "s-sada",
      "emoji": "✈️",
      "weekDate": "2026-09-07",
      "titleHr": "Avion za Boston",
      "titleEn": "The plane to Boston",
      "focusHr": "ići avionom",
      "focusEn": "to go by plane",
      "lines": [
        {
          "hr": "Nikola ide s mamom i tatom.",
          "en": "Nikola goes with mama and tata.",
          "audio": "audio/s-sada/2026-09-07/line01.mp3"
        },
        {
          "hr": "Mama i tata sjede uz njega.",
          "en": "Mama and tata sit next to him.",
          "audio": "audio/s-sada/2026-09-07/line02.mp3"
        },
        {
          "hr": "Tata kaže da sjeda mirno.",
          "en": "Tata says that he should sit still.",
          "audio": "audio/s-sada/2026-09-07/line03.mp3"
        },
        {
          "hr": "Nikola hoće gledati kroz prozor.",
          "en": "Nikola wants to look through the window.",
          "audio": "audio/s-sada/2026-09-07/line04.mp3"
        },
        {
          "hr": "Mama daje mu mali jastuk.",
          "en": "Mama gives him a little pillow.",
          "audio": "audio/s-sada/2026-09-07/line05.mp3"
        },
        {
          "hr": "Avion ide visoko iznad oblaka.",
          "en": "The plane goes high above the clouds.",
          "audio": "audio/s-sada/2026-09-07/line06.mp3"
        },
        {
          "hr": "Nikola vidi more ispod njih.",
          "en": "Nikola sees the sea below them.",
          "audio": "audio/s-sada/2026-09-07/line07.mp3"
        },
        {
          "hr": "Oni idu prema Bostonu sad.",
          "en": "They go toward Boston now.",
          "audio": "audio/s-sada/2026-09-07/line08.mp3"
        },
        {
          "hr": "Oni drže ga za ruku.",
          "en": "They hold him by the hand.",
          "audio": "audio/s-sada/2026-09-07/line09.mp3"
        },
        {
          "hr": "Avion leti tiho kroz noć.",
          "en": "The plane flies quietly through the night.",
          "audio": "audio/s-sada/2026-09-07/line10.mp3"
        }
      ]
    }
  ]
};

const STORY_DATE = WEEK.STORY_DATE;
const STORY_DATE_HR = WEEK.STORY_DATE_HR;
const PREVIOUS_DATE = WEEK.PREVIOUS_DATE;
const PREVIOUS_STORIES = WEEK.PREVIOUS_STORIES;
const STORIES = WEEK.STORIES;

if (typeof module !== "undefined") {
  module.exports = STORIES;
  module.exports.STORY_DATE = STORY_DATE;
  module.exports.STORY_DATE_HR = STORY_DATE_HR;
  module.exports.PREVIOUS_DATE = PREVIOUS_DATE;
  module.exports.PREVIOUS_STORIES = PREVIOUS_STORIES;
}
