// Curated present-tense adventures. 10 lines of 5–6 words each.
// Tara (2) leads Nikola into big-kid play. Baka is staying in this house.

module.exports = {
  tara: {
    id: "s-tara",
    emoji: "🛝",
    variants: [
      {
        titleHr: "Tara pokazuje tobogan",
        titleEn: "Tara shows the slide",
        focusHr: "penjati se",
        focusEn: "to climb",
        lines: [
          { hr: "Nikola i Tara idu u park.", en: "Nikola and Tara go to the park." },
          { hr: "Tara vidi visoki tobogan tamo.", en: "Tara sees the tall slide there." },
          { hr: "Tara kaže hajde svom Nikoli.", en: "Tara says come on to her Nikola." },
          { hr: "Tara se penje gore prva.", en: "Tara climbs up first." },
          { hr: "Nikola ide za njom gore.", en: "Nikola goes up after her." },
          { hr: "Tara se spušta jako brzo.", en: "Tara slides down very fast." },
          { hr: "Nikola se spušta za njom.", en: "Nikola slides down after her." },
          { hr: "Tara zove njega još jednom.", en: "Tara calls him one more time." },
          { hr: "Oni se smiju na dnu.", en: "They laugh at the bottom." },
          { hr: "Tara pokazuje mu put kući.", en: "Tara shows him the way home." },
        ],
      },
      {
        titleHr: "Tara uči loptu",
        titleEn: "Tara teaches the ball",
        focusHr: "udarati loptu",
        focusEn: "to kick the ball",
        lines: [
          { hr: "Tara nosi loptu u park.", en: "Tara carries a ball to the park." },
          { hr: "Ona kaže hajde Nikoli sad.", en: "She says come on to Nikola now." },
          { hr: "Tara udara loptu prema njemu.", en: "Tara kicks the ball toward him." },
          { hr: "Nikola udara loptu natrag njoj.", en: "Nikola kicks the ball back to her." },
          { hr: "Tara trči brzo za loptom.", en: "Tara runs quickly after the ball." },
          { hr: "Nikola trči za njom skupa.", en: "Nikola runs along with her." },
          { hr: "Tara hoće još jednu igru.", en: "Tara wants one more game." },
          { hr: "Ona daje loptu njemu sad.", en: "She gives him the ball now." },
          { hr: "Nikola vidi njezin veliki smiješak.", en: "Nikola sees her big smile." },
          { hr: "Tara zove ga prema kući.", en: "Tara calls him toward home." },
        ],
      },
      {
        titleHr: "Tara uči ples",
        titleEn: "Tara teaches him to dance",
        focusHr: "učiti",
        focusEn: "to teach",
        lines: [
          { hr: "Tara pali glazbu u sobi.", en: "Tara puts music on in the room." },
          { hr: "Tara kaže hajde Nikoli sad.", en: "Tara says come on to Nikola now." },
          { hr: "Tara uči ga plesati sad.", en: "Tara teaches him to dance now." },
          { hr: "Ona pokazuje mu jedan korak.", en: "She shows him one step." },
          { hr: "Nikola ponavlja taj korak polako.", en: "Nikola repeats that step slowly." },
          { hr: "Tara pleše polako pred njim.", en: "Tara dances slowly in front of him." },
          { hr: "Nikola pleše za njom skupa.", en: "Nikola dances along with her." },
          { hr: "Ona daje mu ruku sad.", en: "She gives him her hand now." },
          { hr: "Nikola hoće još jedan korak.", en: "Nikola wants one more step." },
          { hr: "Oni plešu skupa po sobi.", en: "They dance together around the room." },
        ],
      },
    ],
  },
  baka: {
    id: "s-baka",
    emoji: "🍪",
    variants: [
      {
        titleHr: "Baka ujutro kod nas",
        titleEn: "Baka’s morning at our house",
        focusHr: "dati",
        focusEn: "to give",
        lines: [
          { hr: "Baka ustaje rano kod nas.", en: "Baka gets up early at our house." },
          { hr: "Nikola ide k njoj u kuhinju.", en: "Nikola goes to her in the kitchen." },
          { hr: "Baka daje mu toplo mlijeko.", en: "Baka gives him warm milk." },
          { hr: "On vidi kruh na stolu.", en: "He sees bread on the table." },
          { hr: "Baka kaže da je doručak.", en: "Baka says that it is breakfast." },
          { hr: "Nikola hoće još malo kruha.", en: "Nikola wants a little more bread." },
          { hr: "Baka sjedi s njim skupa.", en: "Baka sits together with him." },
          { hr: "Ona pere mu meke ruke.", en: "She washes his soft hands." },
          { hr: "Oni jedu doručak vrlo polako.", en: "They eat breakfast very slowly." },
          { hr: "Baka ljubi njega u čelo.", en: "Baka kisses him on the forehead." },
        ],
      },
      {
        titleHr: "Baka na tržnici",
        titleEn: "Baka at the market",
        focusHr: "kupovati",
        focusEn: "to buy",
        lines: [
          { hr: "Baka i Nikola idu na tržnicu.", en: "Baka and Nikola go to the market." },
          { hr: "Nikola vidi crvene rajčice tamo.", en: "Nikola sees red tomatoes there." },
          { hr: "Baka hoće svježi kruh danas.", en: "Baka wants fresh bread today." },
          { hr: "Ona daje mu jednu krušku.", en: "She gives him one pear." },
          { hr: "Nikola kaže hvala svojoj baki.", en: "Nikola says thank you to his baka." },
          { hr: "Baka kupuje sir za kuću.", en: "Baka buys cheese for the house." },
          { hr: "Oni nose vrećice prema kući.", en: "They carry the bags toward home." },
          { hr: "Nikola ide uz baku polako.", en: "Nikola walks slowly beside baka." },
          { hr: "Baka pokazuje mu žute limune.", en: "Baka shows him yellow lemons." },
          { hr: "Oni se vraćaju kući skupa.", en: "They come back home together." },
        ],
      },
      {
        titleHr: "Baka kuha juhu",
        titleEn: "Baka cooks soup",
        focusHr: "kuhati",
        focusEn: "to cook",
        lines: [
          { hr: "Baka kuha juhu u kuhinji.", en: "Baka cooks soup in the kitchen." },
          { hr: "Nikola stoji pokraj nje sad.", en: "Nikola stands beside her now." },
          { hr: "Baka daje mu drvenu žlicu.", en: "Baka gives him a wooden spoon." },
          { hr: "On miješa juhu vrlo polako.", en: "He stirs the soup very slowly." },
          { hr: "Nikola vidi paru iz lonca.", en: "Nikola sees steam from the pot." },
          { hr: "Baka kaže da je gotovo.", en: "Baka says that it is ready." },
          { hr: "Ona toči juhu njemu prvo.", en: "She pours soup for him first." },
          { hr: "Nikola hoće još jednu žlicu.", en: "Nikola wants one more spoonful." },
          { hr: "Oni jedu juhu za stolom.", en: "They eat soup at the table." },
          { hr: "Baka briše mu mala usta.", en: "Baka wipes his little mouth." },
        ],
      },
      {
        titleHr: "Baka vodi u operu",
        titleEn: "Baka takes him to the opera",
        focusHr: "slušati",
        focusEn: "to listen",
        lines: [
          { hr: "Baka vodi Nikolu u operu.", en: "Baka takes Nikola to the opera." },
          { hr: "Oni idu u dvoranu polako.", en: "They go into the hall slowly." },
          { hr: "Nikola vidi veliku scenu tamo.", en: "Nikola sees the big stage there." },
          { hr: "Baka daje mu svoj program.", en: "Baka gives him her program." },
          { hr: "Glazba počinje jako tiho sad.", en: "The music begins very quietly now." },
          { hr: "Nikola hoće gledati pjevače skupa.", en: "Nikola wants to watch the singers together." },
          { hr: "Baka kaže da sluša pažljivo.", en: "Baka says that he should listen carefully." },
          { hr: "Oni sjede mirno u mraku.", en: "They sit still in the dark." },
          { hr: "Na sceni pjevaju ljudi glasno.", en: "On the stage people sing loudly." },
          { hr: "Baka drži ga za ruku.", en: "Baka holds him by the hand." },
        ],
      },
    ],
  },
  mama: {
    id: "s-odlazak",
    emoji: "🖼️",
    variants: [
      {
        titleHr: "Mama u muzeju",
        titleEn: "Mama at the museum",
        focusHr: "gledati",
        focusEn: "to look",
        lines: [
          { hr: "Mama i Nikola idu u muzej.", en: "Mama and Nikola go to the museum." },
          { hr: "Nikola vidi veliku sliku tamo.", en: "Nikola sees a big painting there." },
          { hr: "Mama pokazuje mu plavo more.", en: "Mama shows him the blue sea." },
          { hr: "On hoće gledati tu sliku.", en: "He wants to look at that painting." },
          { hr: "Mama kaže da je lijepa.", en: "Mama says that it is beautiful." },
          { hr: "Nikola stoji pred slikom mirno.", en: "Nikola stands still in front of the painting." },
          { hr: "Mama daje mu njezinu ruku.", en: "Mama gives him her hand." },
          { hr: "Oni hodaju tiho kroz dvoranu.", en: "They walk quietly through the hall." },
          { hr: "Nikola vidi još jednu sliku.", en: "Nikola sees one more painting." },
          { hr: "Mama vodi ga prema izlazu.", en: "Mama takes him toward the exit." },
        ],
      },
      {
        titleHr: "Šetnja po kvartu",
        titleEn: "A walk around the neighborhood",
        focusHr: "hodati",
        focusEn: "to walk",
        lines: [
          { hr: "Mama i Nikola hodaju ulicom sad.", en: "Mama and Nikola walk down the street now." },
          { hr: "Nikola vidi crveni autobus tamo.", en: "Nikola sees a red bus there." },
          { hr: "Mama kaže da idu polako.", en: "Mama says that they go slowly." },
          { hr: "Pas laje iza visoke ograde.", en: "A dog barks behind a tall fence." },
          { hr: "Nikola hoće mahati tom psu.", en: "Nikola wants to wave to that dog." },
          { hr: "Mama daje mu svoju ruku.", en: "Mama gives him her hand." },
          { hr: "Oni idu pokraj malih dućana.", en: "They walk past the little shops." },
          { hr: "Nikola vidi kruh u izlogu.", en: "Nikola sees bread in the window." },
          { hr: "Mama kupuje vodu za njega.", en: "Mama buys water for him." },
          { hr: "Oni se vraćaju kući skupa.", en: "They come back home together." },
        ],
      },
      {
        titleHr: "Mama pokazuje kvart",
        titleEn: "Mama shows the neighborhood",
        focusHr: "vidjeti",
        focusEn: "to see",
        lines: [
          { hr: "Mama vodi Nikolu oko kvarta.", en: "Mama takes Nikola around the neighborhood." },
          { hr: "Oni idu ispod visokih stabala.", en: "They walk under the tall trees." },
          { hr: "Nikola vidi žuto lišće tamo.", en: "Nikola sees yellow leaves there." },
          { hr: "Mama pokazuje mu ptičje gnijezdo.", en: "Mama shows him a bird’s nest." },
          { hr: "On hoće gledati gnijezdo izbliza.", en: "He wants to look at the nest up close." },
          { hr: "Mama kaže da gleda tiho.", en: "Mama says that he should look quietly." },
          { hr: "Ptica sjedi mirno na grani.", en: "The bird sits still on the branch." },
          { hr: "Nikola daje mami svoju ruku.", en: "Nikola gives mama his hand." },
          { hr: "Oni hodaju dalje niz ulicu.", en: "They walk on down the street." },
          { hr: "Mama nosi ga pred kućom.", en: "Mama carries him in front of the house." },
        ],
      },
    ],
  },
  tata: {
    id: "s-odlazak",
    emoji: "🚲",
    variants: [
      {
        titleHr: "Tata i bicikl",
        titleEn: "Tata and the bike",
        focusHr: "voziti",
        focusEn: "to ride",
        lines: [
          { hr: "Tata drži bicikl za Nikolu.", en: "Tata holds the bicycle for Nikola." },
          { hr: "Nikola sjeda na malo sjedalo.", en: "Nikola sits on the little seat." },
          { hr: "Tata kaže da vozi polako.", en: "Tata says that he should ride slowly." },
          { hr: "Nikola vidi stazu pred sobom.", en: "Nikola sees the path in front of him." },
          { hr: "On hoće voziti sam sad.", en: "He wants to ride by himself now." },
          { hr: "Tata ide uz njega skupa.", en: "Tata goes along beside him." },
          { hr: "Bicikl ide ravno niz stazu.", en: "The bike goes straight down the path." },
          { hr: "Tata drži sjedalo iza njega.", en: "Tata holds the seat behind him." },
          { hr: "Nikola se smije na vjetru.", en: "Nikola laughs in the wind." },
          { hr: "Oni idu natrag prema kući.", en: "They go back toward home." },
        ],
      },
      {
        titleHr: "Tata na moru",
        titleEn: "Tata at the sea",
        focusHr: "plivati",
        focusEn: "to swim",
        lines: [
          { hr: "Tata i Nikola idu na more.", en: "Tata and Nikola go to the sea." },
          { hr: "Nikola vidi velike valove tamo.", en: "Nikola sees the big waves there." },
          { hr: "Tata kaže da je toplo.", en: "Tata says that it is warm." },
          { hr: "Nikola hoće u plavu vodu.", en: "Nikola wants to go in the blue water." },
          { hr: "Tata daje mu svoju ruku.", en: "Tata gives him his hand." },
          { hr: "Oni gaze u more polako.", en: "They wade into the sea slowly." },
          { hr: "Nikola pliva uz tatu blizu.", en: "Nikola swims close beside tata." },
          { hr: "Valovi dolaze nježno prema njima.", en: "The waves come gently toward them." },
          { hr: "Tata diže ga iznad vala.", en: "Tata lifts him above a wave." },
          { hr: "Oni se smiju na suncu.", en: "They laugh in the sun." },
        ],
      },
      {
        titleHr: "Lopta s tatom",
        titleEn: "A ball with tata",
        focusHr: "trčati",
        focusEn: "to run",
        lines: [
          { hr: "Tata donosi loptu u dvorište.", en: "Tata brings a ball into the yard." },
          { hr: "Nikola vidi loptu u travi.", en: "Nikola sees the ball in the grass." },
          { hr: "Tata kaže hajde prema njemu.", en: "Tata says come on toward him." },
          { hr: "Nikola hoće udariti tu loptu.", en: "Nikola wants to kick that ball." },
          { hr: "Tata daje mu loptu prvo.", en: "Tata gives him the ball first." },
          { hr: "Nikola udara loptu prema tati.", en: "Nikola kicks the ball toward tata." },
          { hr: "Oni trče skupa za loptom.", en: "They run together after the ball." },
          { hr: "Tata ide u gol sad.", en: "Tata goes in goal now." },
          { hr: "Nikola šalje loptu u gol.", en: "Nikola sends the ball into the goal." },
          { hr: "Tata tapše ga zbog pogotka.", en: "Tata claps for him because of the goal." },
        ],
      },
    ],
  },
  sada: {
    id: "s-sada",
    emoji: "✈️",
    variants: {
      plane: {
        titleHr: "Avion za Boston",
        titleEn: "The plane to Boston",
        focusHr: "ići avionom",
        focusEn: "to go by plane",
        emoji: "✈️",
        lines: [
          { hr: "Nikola ide s mamom i tatom.", en: "Nikola goes with mama and tata." },
          { hr: "Mama i tata sjede uz njega.", en: "Mama and tata sit next to him." },
          { hr: "Tata kaže da sjeda mirno.", en: "Tata says that he should sit still." },
          { hr: "Nikola hoće gledati kroz prozor.", en: "Nikola wants to look through the window." },
          { hr: "Mama daje mu mali jastuk.", en: "Mama gives him a little pillow." },
          { hr: "Avion ide visoko iznad oblaka.", en: "The plane goes high above the clouds." },
          { hr: "Nikola vidi more ispod njih.", en: "Nikola sees the sea below them." },
          { hr: "Oni idu prema Bostonu sad.", en: "They go toward Boston now." },
          { hr: "Oni drže ga za ruku.", en: "They hold him by the hand." },
          { hr: "Avion leti tiho kroz noć.", en: "The plane flies quietly through the night." },
        ],
      },
      family: {
        titleHr: "Tatina obitelj",
        titleEn: "Tata’s family",
        focusHr: "rođaci",
        focusEn: "relatives",
        emoji: "👨‍👩‍👧‍👦",
        lines: [
          { hr: "Tata vodi Nikolu kod rođaka.", en: "Tata takes Nikola to the relatives." },
          { hr: "Nikola vidi tatinu obitelj tamo.", en: "Nikola sees tata’s family there." },
          { hr: "Oni ga grle jako nježno.", en: "They hug him very gently." },
          { hr: "Nikola hoće sjediti uz tatu.", en: "Nikola wants to sit next to tata." },
          { hr: "Tata kaže da su svoji.", en: "Tata says that they are family." },
          { hr: "Rođaci daju mu male darove.", en: "The relatives give him little gifts." },
          { hr: "Nikola ide među rođake polako.", en: "Nikola goes among the relatives slowly." },
          { hr: "Oni jedu skupa za stolom.", en: "They eat together at the table." },
          { hr: "Tata pokazuje mu svaku osobu.", en: "Tata shows him each person." },
          { hr: "Nikola se smije novim licima.", en: "Nikola laughs at the new faces." },
        ],
      },
      beach: {
        titleHr: "More na plaži",
        titleEn: "The ocean at the beach",
        focusHr: "plivati",
        focusEn: "to swim",
        emoji: "🌊",
        lines: [
          { hr: "Obitelj ide na pješčanu plažu.", en: "The family goes to the sandy beach." },
          { hr: "Nikola vidi plavo more tamo.", en: "Nikola sees the blue sea there." },
          { hr: "Tata kaže da je slano.", en: "Tata says that it is salty." },
          { hr: "Nikola hoće u vodu odmah.", en: "Nikola wants to go in the water right away." },
          { hr: "Mama daje mu svoju ruku.", en: "Mama gives him her hand." },
          { hr: "Oni idu u valove polako.", en: "They go into the waves slowly." },
          { hr: "Nikola pliva malo uz tatu.", en: "Nikola swims a little beside tata." },
          { hr: "Voda liže mu male noge.", en: "The water licks his little feet." },
          { hr: "On se smije zbog valova.", en: "He laughs because of the waves." },
          { hr: "Sunce sja im na leđa.", en: "The sun shines on their backs." },
        ],
      },
      krstenje: {
        titleHr: "Priprema za krštenje",
        titleEn: "Getting ready for the baptism",
        focusHr: "obitelj",
        focusEn: "family",
        emoji: "⛪️",
        lines: [
          { hr: "Obitelj ide u crkvu danas.", en: "The family goes to church today." },
          { hr: "Nikola vidi bijelu odjeću tamo.", en: "Nikola sees white clothes there." },
          { hr: "Mama kaže da je spremno.", en: "Mama says that it is ready." },
          { hr: "Tata drži Nikolu na rukama.", en: "Tata holds Nikola in his arms." },
          { hr: "Baka daje mu mali osmijeh.", en: "Baka gives him a little smile." },
          { hr: "Svi hoće miran lijepi dan.", en: "Everyone wants a peaceful lovely day." },
          { hr: "Teta Emma sjedi u klupi.", en: "Teta Emma sits in the pew." },
          { hr: "Barba Marco stoji pokraj tate.", en: "Barba Marco stands beside tata." },
          { hr: "Voda čeka na krštenje sad.", en: "The water waits for the baptism now." },
          { hr: "Obitelj pjeva tiho u crkvi.", en: "The family sings quietly in the church." },
        ],
      },
      mamaBirthday: {
        titleHr: "Mamin rođendan",
        titleEn: "Mama’s birthday",
        focusHr: "rođendan",
        focusEn: "birthday",
        emoji: "🎂",
        lines: [
          { hr: "Danas je mamin rođendan kod kuće.", en: "Today is mama’s birthday at home." },
          { hr: "Nikola vidi tortu na stolu.", en: "Nikola sees a cake on the table." },
          { hr: "Tara kaže sretan rođendan mami.", en: "Tara says happy birthday to mama." },
          { hr: "Nikola hoće puhati svjećice skupa.", en: "Nikola wants to blow out the candles together." },
          { hr: "Mama daje mu komad torte.", en: "Mama gives him a piece of cake." },
          { hr: "Teta Emma pjeva uz stol.", en: "Teta Emma sings at the table." },
          { hr: "Barba Marco tapše u ritmu.", en: "Barba Marco claps in rhythm." },
          { hr: "Baka sjedi pokraj mame sad.", en: "Baka sits beside mama now." },
          { hr: "Oni idu u zagrljaj skupa.", en: "They go into a hug together." },
          { hr: "Mama ljubi Nikolu od sreće.", en: "Mama kisses Nikola out of joy." },
        ],
      },
      bakaBirthday: {
        titleHr: "Bakin rođendan",
        titleEn: "Baka’s birthday",
        focusHr: "rođendan",
        focusEn: "birthday",
        emoji: "🌸",
        lines: [
          { hr: "Danas je bakin rođendan kod nas.", en: "Today is baka’s birthday at our house." },
          { hr: "Nikola vidi cvijeće na stolu.", en: "Nikola sees flowers on the table." },
          { hr: "On kaže sretan rođendan baki.", en: "He says happy birthday to baka." },
          { hr: "Baka hoće kolač od jabuka.", en: "Baka wants apple cake." },
          { hr: "Mama daje baki taj kolač.", en: "Mama gives baka that cake." },
          { hr: "Tara pleše pred bakom veselo.", en: "Tara dances happily in front of baka." },
          { hr: "Teta Emma donosi mali dar.", en: "Teta Emma brings a little gift." },
          { hr: "Barba Marco sjedi uz baku.", en: "Barba Marco sits next to baka." },
          { hr: "Oni idu oko stola skupa.", en: "They go around the table together." },
          { hr: "Baka grli Nikolu jako nježno.", en: "Baka hugs Nikola very gently." },
        ],
      },
      taraBirthday: {
        titleHr: "Tarin rođendan",
        titleEn: "Tara’s birthday",
        focusHr: "rođendan",
        focusEn: "birthday",
        emoji: "🎈",
        lines: [
          { hr: "Danas je Tarin rođendan kod kuće.", en: "Today is Tara’s birthday at home." },
          { hr: "Nikola vidi šarene balone tamo.", en: "Nikola sees colorful balloons there." },
          { hr: "Tara kaže hajde prema torti.", en: "Tara says come on toward the cake." },
          { hr: "Nikola hoće pjevati s njom.", en: "Nikola wants to sing with her." },
          { hr: "Mama daje Tari mali dar.", en: "Mama gives Tara a little gift." },
          { hr: "Tara trči oko stola sretna.", en: "Tara runs happily around the table." },
          { hr: "Teta Emma pali svjećice polako.", en: "Teta Emma lights the candles slowly." },
          { hr: "Barba Marco tapše od sreće.", en: "Barba Marco claps with joy." },
          { hr: "Oni idu puhati svjećice skupa.", en: "They go to blow out the candles together." },
          { hr: "Tara zove Nikolu u ples.", en: "Tara calls Nikola into the dance." },
        ],
      },
    },
  },
};
